### ISSUE TITLE
Licenc

### ISSUE THREAD

**Issue by horverno** [ABC-iRobotics/ros_course_materials_hu#1]
Kedves @TamasDNagy!

Készülő tananyaghoz szeretnék a [3D transzformációkról](https://abc-irobotics.github.io/ros_course_materials_hu/05_da_vinci/) szóló részből átvenni, természetesen, amennyiben ez lehetséges. Bármilyen megengedő licensz hozzáadása a repóhoz lehetővé tenné ezt (MIT, GPL-3.0, Apache stb.). Köszönöm!

**Comment by tlevendovics** [comment]
Kedves @horverno,

Örülök a megkeresésnek! A forrás megjelölésével természetesen felhasználhatod az anyagot. Hozzáadtam a licenszt a repóhoz (CC BY-NC-SA).
